[package]
name = "cacheviewnut"
version = "0.0.1"
authors = ["Magnus Hoff <maghoff@gmail.com>"]

[dependencies]
num = "~0.1"
hyper = "~0.6.14"
rustc-serialize = "~0.3"
regex = "~0.1"
iron = "~0.2"
router = "0.0.15"
