[package]
name = "cacheviewnut"
version = "0.0.1"
authors = ["Magnus Hoff <maghoff@gmail.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
num = "~0.1"
hyper = "0.7"
rustc-serialize = "0.3.22"
regex = "~0.1"
iron = "0.2"
router = "0.0.15"
crossbeam = "0.2.0"
